# article-04: 窗口居中与多显示器适配
.PHONY: run build build-release clean

run:
	cargo run --bin article-04

build:
	cargo build --bin article-04

build-release:
	cargo build --release --bin article-04

clean:
	cargo clean
